
spring:
    application:
        name: cloudx-gateway

server:
    port: 32063

eureka:
    client:
        registerWithEureka: false  
        fetchRegistry: false      
        serviceUrl:
            defaultZone: http://127.0.0.1:32062/eureka/

feign:
  hystrix:
    enabled: true            
